### ISSUE TITLE
Telegram group Topics

### ISSUE THREAD

**Issue by cuteroadkill** [spkesDE/com.spkes.telegramNotifications#14]
Suggestion to be able to send to Group chat Topics.

Send Message <Message> to Chat <Chat> into Topic <Topic>Create Topic <Topic> in Chat <Chat>

or

Send Message <Message> to Chat <Chat> into Topic <Topic> in Chat <Chat>
(if topic already existing)

**Comment by enyineer** [comment]
@spkesDE first of all, thank you for this awesome app. I first thought about implementing my own - but your's is almost perfect for my needs. So why reinvent the wheel?

One issue I have though is with the topics and the commands. I'd like to distinguish the "A message from <topic> is received, as I'd like to split out each zone into it's own topic. I can already chose each topic as the originating chat:

![tg-flow](https://github.com/spkesDE/com.spkes.telegramNotifications/assets/27201677/fcccf6fd-0fff-4eb6-ac9f-b3e9cc23faee)

However, all cards get triggered even if the message was written into one topic.

This is what my topics look like:

![tg-topics](https://github.com/spkesDE/com.spkes.telegramNotifications/assets/27201677/2ad3bfb7-6120-4653-a663-fc363cea544f)

Am I using the card wrong or is that not implemented yet?

My first thought was to just use commands (like /wohnzimmer) and to set them as available commands via Botfather. The problem is that the bot overrides these commands after some time / restart of the app. So this isn't working either.

Any good suggestions?

**Comment by enyineer** [comment]
I have proposed #23 for fixing the topic filter in the receive-message-from-chat trigger card.

**Comment by spkesDE** [comment]
See #23 for my answer :)
